name: 'Mirror to GitHub'
branding:
  icon: 'download-cloud'
  color: 'white'
description: 'Mirror a repository to GitHub'
inputs:
  origin:
    description: 'URL of remote git repository'
    required: true
  mirror:
    description: "github repo containing the mirror in format user/repo"
    required: true
  GITHUB_TOKEN:
    description: 'set this to the value of a secret containing a token with read/write permissions for the mirror repo'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.origin }}
    - ${{ inputs.mirror }}
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
